import { Link } from "react-router-dom";
import type { ReactNode } from "react";
import { ArrowLeft, CheckCircle2, FileText, Headphones, LockKeyhole } from "lucide-react";
import SiteChrome from "@/components/SiteChrome";
import EnquiryForm from "@/components/EnquiryForm";

export default function Apply() {
  return <SiteChrome><section className="bg-sky-50" data-testid="apply-hero-section"><div className="mx-auto max-w-7xl px-6 py-14 lg:px-8 lg:py-20"><Link to="/" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-700" data-testid="apply-back-link"><ArrowLeft className="size-4" /> Back to home</Link><div className="mt-8 grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="section-kicker" data-testid="apply-hero-kicker">Online application</p><h1 className="section-display" data-testid="apply-hero-title">Let’s find a funding path that fits.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600" data-testid="apply-hero-description">Share a few details and our advisor will call you within business hours. No pressure, no confusing forms.</p></div><div className="grid gap-3 sm:grid-cols-3"><Promise icon={<LockKeyhole />} title="Private" text="Your details stay confidential" testId="private" /><Promise icon={<Headphones />} title="Human help" text="Real advisor, clear answers" testId="human" /><Promise icon={<FileText />} title="Simple start" text="Just the essentials first" testId="simple" /></div></div></div></section><section className="mx-auto grid max-w-7xl gap-10 px-6 py-20 lg:grid-cols-[0.7fr_1.3fr] lg:px-8" data-testid="apply-form-section"><div className="lg:pt-4"><p className="section-kicker" data-testid="apply-form-kicker">Your details, your pace</p><h2 className="section-title" data-testid="apply-form-title">A better conversation starts here.</h2><div className="mt-8 space-y-5"><Step number="01" title="Tell us your goal" text="Choose the kind of loan or funding you are exploring." testId="step-1" /><Step number="02" title="We review the context" text="An advisor looks at your requirements and calls you." testId="step-2" /><Step number="03" title="You decide with clarity" text="We explain suitable options before you take action." testId="step-3" /></div><div className="mt-8 flex items-start gap-3 rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-800" data-testid="apply-trust-note"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-600" /> We never ask for an upfront payment in exchange for a promise of approval.</div></div><EnquiryForm /></section></SiteChrome>;
}

function Promise({ icon, title, text, testId }: { icon: ReactNode; title: string; text: string; testId: string }) { return <div className="rounded-2xl border border-sky-100 bg-white p-4" data-testid={`apply-promise-${testId}`}><span className="text-sky-600">{icon}</span><strong className="mt-3 block text-sm font-bold text-slate-900" data-testid={`apply-promise-${testId}-title`}>{title}</strong><span className="mt-1 block text-xs leading-5 text-slate-500" data-testid={`apply-promise-${testId}-text`}>{text}</span></div>; }
function Step({ number, title, text, testId }: { number: string; title: string; text: string; testId: string }) { return <div className="flex gap-4" data-testid={testId}><span className="font-mono text-sm font-bold text-sky-600" data-testid={`${testId}-number`}>{number}</span><div><h3 className="font-heading text-base font-bold text-slate-900" data-testid={`${testId}-title`}>{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600" data-testid={`${testId}-text`}>{text}</p></div></div>; }